name: 'OCM Simple Action'
description: 'Simplify using OCM'
inputs:
  images:
    description: 'Array of image tags to be added as resources'
    required: true
# outputs:
runs:
  using: "composite"
  steps:
  - id: init
    shell: bash
    run: |
      pip install -r ${{ github.action_path }}/requirements.txt
  - id: python
    shell: python
    env:
      ocm_images: ${{ inputs.images }}
    run: |
      import sys
      sys.path.append('${{ github.action_path }}')
      import main
      main.main()

