name: Test Simple OCM
on:
  workflow_dispatch:
jobs:
  call-action:
    name: call simple ocm action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Simple OCM component creation
        uses: jensh007/simple-action@main
        with:
          comp_root: ghcr.io/jensh007/microblog/ocm
          name: github.com/jensh007/microblog
          version: 1.0.0
          provider: github.com/jensh007
          images: |
            - ghcr.io/jensh007/ocm//ocm.software/ocmcli-image:0.3.0-rc.2
            - foo/bar:1.0.0
          helm_charts: |
            - charts/mariadb.tgz:11.4.2.
            - https://charts.bitnami.com/bitnami/mariadb:10.11.2
          files: |
            - name: README.md
              content_type: text/markdown
          references: |
            - name: mariadb
              componentName: github.com/jensh007/mariadb:10.11.2
              version: '10.11.2'
          labels: |
            - name: last-scanned
              value: 2023-06-21T18:00:00
            - name: registry-provider
              value: Github
      - name: Upload OCM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ocm
          path: gen/ca