name: Test Simple OCM
on:
  workflow_dispatch:
jobs:
  call-action:
    name: call simple ocm action
    runs-on: ubuntu-latest
    steps:
      - name: test simple ocm
        uses: jensh007/simple-action@main
        with:
          comp_root: ghcr.io/jensh007/microblog/ocm
          name: microblog
          version: 1.0.0
          provider: github.com/jensh007
          images: |
            - ghcr.io/jensh007/ocm//ocm.software/ocmcli-image:0.3.0-rc.2
            - foo/bar:1.0.0
          helm_charts: |
            - charts/mariadb-11.4.2.tgz
            - https://charts.bitnami.com/bitnami/mariadb:10.11.2
          files: |
            - name: readme.md
              content-type: text/markdown
          references: |
            - name: mariadb
              componentName: github.com/jensh007/mariadb:10.11.2
              version: ${MARIADB_VERSION}
          labels: |
            - key: last-scanned
              value: 2023-06-21T18:00:00
            - position: resources/images
              key: registry-provider
              value: Google